# Site
repository: lmm0212/lmm0212.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 刘蔓蔓
title: The most beautiful girl of FanXian
email: 3055066676@qq.com
website: www.github.com/lmm0212

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  lmm0212
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 The web belongs to Liu Manman(刘蔓蔓）, a beautiful girl studying in North China University of Water Resources and Electric Power. Besides, She is also the most pretty girl in the world.
content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/happywangmakeit
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  happywangmakeit/happywangmakeit
  #           icon: fab fa-github
  #           url: github.com/happywangmakeit/happywangmakeit.github.io
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  # - title: Her boyfriend # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: right
  #       title: Photo by the Corn tower of Zhengzhou
  #       # link: https://deepvideolab.top/
  #       # link_text: Happy day!
  #       sub_title: Happy day!
  #       caption: 31 March 2024
  #       quote: >
  #         Happy day!
  #       description: | # this will include new lines to allow paragraphs
  #         Today We go to visit the famous Corn tower in Zhengzhou! We have a happy time and see an amazing landscape of the tower! With the delight mood, we ask the passer-by to help us take the photo of two.

  #     ![Trees](images/landscape-trees.jpg "Trees")
  # - title: Education # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: Peking University
  #       caption: September 2021 - Present
  #       sub_title: Intelligent science and technology(with a double major in economics)
  #       quote: >
  #         Established in 1898
  #       description: | # this will include new lines to allow paragraphs
  #         2022.10 - 2023.6 Minister of Life Department of Peking University Student Union
          
  #         2022.6 - 2023.6 Minister of Public Relations, Student Union, School of Government Management
          
  #         <mark>Previous Awards</mark>:  National Encouragement Scholarship, Peking University third-class Scholarship, Peking University Merit student, Third prize of Peking University Challenge Cup and other awards。

  - title: A happy day!
    layout: text
    content: | # this will include new lines to allow paragraphs
      - March 31 2024
      
      Today We go to visit the famous Corn tower in Zhengzhou! We have a happy time and see an amazing landscape of the tower! With the delight mood, we ask the passer-by to help us take the photo of two.

      Look at this cool image!  
      <img src="images/anphoto.png" alt="Photo by the Corn tower of Zhengzhou" style="width: 400px; height: 250px;">

  - title: A cute video
    layout: text
    content: | # this will include new lines to allow paragraphs
      - April 10 2024

      I'm so cute!
      
      <video width="400" height="700" controls>
        <source src="images/dance.mp4" type="video/mp4">
        Your browser does not support the video tag.
      </video>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
